CREATE TABLE ULEAPP_FINANCECR.CERTIFICATE_INFO (
  ID NUMBER(11) PRIMARY KEY NOT NULL, 
  BUSI_NAME VARCHAR2(255) NOT NULL  ,
  SYS_NAME VARCHAR2(255) NOT NULL ,
  CER_SEND_TYPE NUMBER(10) NOT NULL  ,
  CER_TYPE NUMBER(10) NOT NULL ,
  EXPIRATION_DATE VARCHAR2(15)  ,
  CHANNEL_CODE VARCHAR2(50) ,
  EMAIL VARCHAR2(50) NOT NULL  ,
  CER_OUT_TYPE NUMBER(10)  ,
  CER_OUT_FILENAME VARCHAR2(250)  ,
  CER_NAME VARCHAR2(50) NOT NULL  ,
  DOWN_PASSWORD VARCHAR2(255)  ,
  REMARK VARCHAR2(255) ,
  CER_ENV NUMBER(10) ,
  CER_CONTENT CLOB ,
  CREATE_TIME TIMESTAMP,
  EDIT_TIME TIMESTAMP  
) TABLESPACE TBS_FINANCECR_DATA;

COMMENT ON COLUMN ULEAPP_FINANCECR.CERTIFICATE_INFO.ID IS '主键';
COMMENT ON COLUMN ULEAPP_FINANCECR.CERTIFICATE_INFO.BUSI_NAME IS '业务单元名';
COMMENT ON COLUMN ULEAPP_FINANCECR.CERTIFICATE_INFO.SYS_NAME IS '模块名';
COMMENT ON COLUMN ULEAPP_FINANCECR.CERTIFICATE_INFO.CER_SEND_TYPE IS '证书颁发主体 1.邮乐颁发 2.外部颁发';
COMMENT ON COLUMN ULEAPP_FINANCECR.CERTIFICATE_INFO.CER_TYPE IS '证书类型 1.公钥 2.私钥 3.PFX公私钥';
COMMENT ON COLUMN ULEAPP_FINANCECR.CERTIFICATE_INFO.EXPIRATION_DATE IS '证书过期时间';
COMMENT ON COLUMN ULEAPP_FINANCECR.CERTIFICATE_INFO.CHANNEL_CODE IS '外部颁发证书的通道编码';
COMMENT ON COLUMN ULEAPP_FINANCECR.CERTIFICATE_INFO.EMAIL IS 'EMAIL地址';
COMMENT ON COLUMN ULEAPP_FINANCECR.CERTIFICATE_INFO.CER_OUT_TYPE IS '外部证书类型 1.文件证书 2.秘钥串证书';
COMMENT ON COLUMN ULEAPP_FINANCECR.CERTIFICATE_INFO.CER_OUT_FILENAME IS '外部证书原始文件名';
COMMENT ON COLUMN ULEAPP_FINANCECR.CERTIFICATE_INFO.CER_NAME IS '生成的文件证书名(服务器保存)';
COMMENT ON COLUMN ULEAPP_FINANCECR.CERTIFICATE_INFO.DOWN_PASSWORD IS '访问文件夹服务的密码';

COMMENT ON COLUMN ULEAPP_FINANCECR.CERTIFICATE_INFO.REMARK IS '预留字段';
COMMENT ON COLUMN ULEAPP_FINANCECR.CERTIFICATE_INFO.CER_ENV IS '证书使用环境 1.开发 2.测试 3.生产';
COMMENT ON COLUMN ULEAPP_FINANCECR.CERTIFICATE_INFO.CER_CONTENT IS '证书内容';
COMMENT ON COLUMN ULEAPP_FINANCECR.CERTIFICATE_INFO.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN ULEAPP_FINANCECR.CERTIFICATE_INFO.EDIT_TIME IS '修改时间';

CREATE TABLE ULEAPP_FINANCECR.SYSTEM_LOG (
  ID NUMBER(11) PRIMARY KEY NOT NULL, 
  SYSTEM_CODE VARCHAR2(50) NOT NULL ,
  REQ_SEQUENCE VARCHAR2(50) NOT NULL,
  FUNCTION_ID VARCHAR2(50) NOT NULL  ,
  REQUEST_CONTENT CLOB  ,
  RESPONSE_CONTENT CLOB ,
  USE_TIME NUMBER(11) NOT NULL ,
  CREATE_TIME TIMESTVARCHAR2,
  REMARK VARCHAR2(255)
) TABLESPACE TBS_FINANCECR_DATA;


COMMENT ON COLUMN ULEAPP_FINANCECR.SYSTEM_LOG.ID IS '主键';
COMMENT ON COLUMN ULEAPP_FINANCECR.SYSTEM_LOG.SYSTEM_CODE IS '系统标识';
COMMENT ON COLUMN ULEAPP_FINANCECR.SYSTEM_LOG.REQ_SEQUENCE IS '请求序列';
COMMENT ON COLUMN ULEAPP_FINANCECR.SYSTEM_LOG.FUNCTION_ID IS '请求业务功能码';
COMMENT ON COLUMN ULEAPP_FINANCECR.SYSTEM_LOG.REQUEST_CONTENT IS '请求内容';
COMMENT ON COLUMN ULEAPP_FINANCECR.SYSTEM_LOG.RESPONSE_CONTENT IS '响应内容';
COMMENT ON COLUMN ULEAPP_FINANCECR.SYSTEM_LOG.USE_TIME IS '请求耗时MS';

COMMENT ON COLUMN ULEAPP_FINANCECR.SYSTEM_LOG.CREATE_TIME IS '创建时间';
COMMENT ON COLUMN ULEAPP_FINANCECR.SYSTEM_LOG.REMARK IS '预留字段';
   
CREATE TABLE ULEAPP_FINANCECR.TASK_SCHEDULE  (
  ID NUMBER(11) NOT NULL,
  JOB_NAME varchar2(150) ,
  JOB_GROUP VARCHAR2(150) ,
  CRON_EXPRESSION VARCHAR2(150) ,
  BEAN_CLASS VARCHAR2(300) ,
  SPRING_ID VARCHAR2(150),
  METHOD_NAME VARCHAR2(150) ,
  JOB_STATUS VARCHAR2(6) ,
  IS_CONCURRENT VARCHAR2(6) ,
  DESCRIPTION VARCHAR2(600) ,
  CREATE_TIME TIMESTAMP,
  UPDATE_TIME TIMESTAMP 
) TABLESPACE TBS_FINANCECR_DATA;
COMMENT ON COLUMN ULEAPP_FINANCECR.TASK_SCHEDULE.JOB_STATUS IS '0没启动，1启动';
COMMENT ON COLUMN ULEAPP_FINANCECR.TASK_SCHEDULE.IS_CONCURRENT IS '是否等待上个任务完成，0是等待 1是不等待';


CREATE SEQUENCE  ULEAPP_FINANCECR.SEQ_CERTIFICATE_INFO 
MINVALUE 1 
MAXVALUE 999999999 
INCREMENT BY 1 
START WITH 1 
CACHE 20 NOORDER  CYCLE ;
  
     
CREATE SEQUENCE  ULEAPP_FINANCECR.SEQ_SYSTEM_LOG 
MINVALUE 1 
MAXVALUE 999999999 
INCREMENT BY 1 
START WITH 1 
CACHE 20 NOORDER  CYCLE ;

CREATE SEQUENCE  ULEAPP_FINANCECR.SEQ_TASK_SCHEDULE 
MINVALUE 1 
MAXVALUE 999999999 
INCREMENT BY 1 
START WITH 1 
CACHE 20 NOORDER  CYCLE ;

