server:
  #端口号
  port: 8767
  #项目名，如果不设定，默认是 /
  servlet:
    context-path: /demo-service
  tomcat:
    uri-encoding: UTF-8

dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address:  nacos://192.168.116.9:8848?backup=192.168.116.9:8847,192.168.116.9:8846
  scan:
    base-packages: com.ule.demo.service.api.impl
  protocol:
    name: dubbo
    port: -1

#spring相关配置
spring:
  application:
    name: demo-service
  boot:
    admin:
      client:
        username: fanxueli
        password: 123456
        url:
          - http://192.168.116.188:9000/springboot-admin
          - http://192.168.116.9:9000
        register-once: false
        instance:
#          name: demo-service
#          prefer-ip: true
#          service-url: http://192.168.116.188:8767/demo-service
#springboot admin  start
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
info:
  author: 'Fanxunli'
  version: '1.0.0'
logging:
  file: '/home/sivan/logs/demo-service.log'
#springboot admin  end

#mybatis配置
mybatis:
  typeAliasesPackage: com.ule.demo.common.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: 'null'
    #驼峰转换
    map-underscore-to-camel-case: true
    use-generated-keys: false

pagehelper:
  helperDialect: oracle
  #启用合理化时，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页
  #<!-- 禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据
  reasonable: true
  # 设置为true时，如果pageSize=0或者RowBounds.limit = 0就会查询出全部的结果 -->
  #（相当于没有执行分页查询，但是返回结果仍然是Page类型）
  pageSizeZero: true
  #支持通过Mapper接口参数来传递分页参数
  supportMethodsArguments: true
  # 自定义参数名
  #params: count=countSql;pageNum=start;pageSize=limit;
  #always总是返回PageInfo类型,check检查返回类型是否为PageInfo,none返回Page
  returnPageInfo: check
#tk.mybatis 通用maper配置
mapper:
  not-empty: false
  identity: ORACLE
  mappers:
    - com.ule.demo.service.common.BaseMapper
  #SelectKey需要注意order属性，像MySQL一类支持自动增长类型的数据库中，order需要设置为after才会取到正确的值,像Oracle这样取序列的情况，需要设置为before，否则会报错
  order: before
#service服务提供的功能方法所在的包路径
handler.package: com.ule.demo.service.handler