server:
  #端口号
  port: 8080
  #项目名，如果不设定，默认是 /
  servlet:
    context-path: /demo-schedule
  tomcat:
    uri-encoding: UTF-8
#spring相关配置
spring:
  mvc:
    view:
      # 页面默认前缀目录
      prefix: /WEB-INF/jsp
      # 响应页面默认后缀
      suffix: .jsp
  application:
    name: demo-schedule

#自定义参数
#访问service服务的地址
serviceUrl: http://localhost:8766/demo-service/api/v1.0